on:
  push:
    branches: ['main']

jobs:
  "_1":
    runs-on: ubuntu-24.04
    steps:
      - run: echo what
  "_2": { name: "${{ fromJSON('\"test\"') }}", needs: [_1], uses: ./.github/workflows/one-job.yaml }
  "_3": { needs: [_2], uses: ./.github/workflows/one-job.yaml }
