on:
  push:
    branches: ['main']

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo what
  job2:
    runs-on: ubuntu-24.04
    needs: [job1]
    if: ${{ !cancelled() && !failure() && fromJSON('false') }}
    strategy:
      matrix:
        include: ${{ fromJSON('[]') }}
    steps:
      - run: echo whatt
  job3:
    name: ${{ fromJSON('""') }}
    runs-on: ubuntu-24.04
    needs: [job2]
    if: ${{ !cancelled() && !failure() && fromJSON('false') }}
    strategy:
      matrix:
        include: ${{ fromJSON('[]') }}
    steps:
      - run: echo whatt
  job4:
    if: ${{ !cancelled() && !failure() }}
    runs-on: ubuntu-24.04
    needs: [job3]
    steps:
      - run: echo whatt
