on:
  push:
    branches: ['main']

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo what
  job2:
    runs-on: ubuntu-24.04
    needs: [job1]
    if: fromJSON('false')
    strategy:
      matrix:
        include: ${{ fromJSON('[]') }}
    steps:
      - run: echo whatt
  job3:
    runs-on: ubuntu-24.04
    needs: [job2]
    if: fromJSON('false')
    strategy:
      matrix:
        include: ${{ fromJSON('[]') }}
    steps:
      - run: echo whatt
  job4:
    runs-on: ubuntu-24.04
    needs: [job3]
    steps:
      - run: echo whatt
